FROM python:3.9-slim-buster

WORKDIR /app

COPY dashboard/requirements.txt ./
# RUN apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev \
#     && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard/realtime_dashboard_streamlit.py .

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "realtime_dashboard_streamlit.py", "--server.port=8501", "--server.headless=true"]