FROM python:3.9-slim-buster

WORKDIR /app

COPY dashboard/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard/realtime_dashboard_streamlit.py .

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "realtime_dashboard_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]