FROM python:3.9-slim-buster

WORKDIR /app

COPY data-processor/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY data-processor/processor.py .

CMD ["python", "processor.py"]