apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.delhiOtdApiKey.name }}
  labels:
    {{- include "realtime-app.labels" . | nindent 4 }}
type: Opaque
data:
  DELHI_OTD_API_KEY: {{ .Values.ingestor.delhiOtdApiKey | b64enc | quote }} # Provided via GitHub Actions