# helm/realtime-app/templates/delhi-otd-api-key-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.delhiOtdApiKey.name }}
  labels:
    {{- include "realtime-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.delhiOtdApiKey.key }}: {{ .Values.secrets.delhiOtdApiKey.value | default "" | b64enc | quote }}