apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: influxdb
    {{- include "realtime-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: influxdb
    {{- include "realtime-app.selectorLabels" . | nindent 4 }}