apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.influxdbTokenSecretName }}
  labels:
    {{- include "realtime-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.application.influxdbTokenSecretKey }}: {{ .Values.application.influxdbToken | default "" | b64enc | quote }}