apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.influxdb.initialAdminTokenSecretName }}
  labels:
    {{- include "realtime-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.influxdb.initialAdminTokenSecretKey }}: {{ .Values.influxdb.initialAdminToken | default "" | b64enc | quote }}