apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.influxdb.initialAdminPasswordSecretName }}
  labels:
    {{- include "realtime-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.influxdb.initialAdminPasswordSecretKey }}: {{ .Values.influxdb.initialAdminPassword | default "" | b64enc | quote }}