apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "realtime-app.fullname" . }}-mosquitto-config
  labels:
    {{- include "realtime-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt-broker
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true 
    persistence true
    persistence_location /mosquitto/data/