apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  labels:
    app.kubernetes.io/name: mqtt
    {{- include "realtime-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mqtt.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt
      {{- include "realtime-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt
        {{- include "realtime-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "realtime-app.serviceAccountName" . }}
      containers:
        - name: mqtt
          image: "{{ .Values.mqtt.image }}"
          ports:
            - containerPort: 1883
          resources:
            {{- toYaml .Values.mqtt.resources | nindent 12 }}
