apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  labels:
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/component: mqtt
    {{- include "realtime-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mqtt.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt
      {{- include "realtime-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt
        {{- include "realtime-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "realtime-app.serviceAccountName" . }}
      containers:
        - name: mqtt
          image: "{{ .Values.mqtt.image }}"
          ports:
            - containerPort: {{ .Values.mqtt.service.port }}
          resources:
            {{- toYaml .Values.mqtt.resources | nindent 12 }}
          volumeMounts:
            - name: mosquitto-config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config-volume
          configMap:
            name: {{ include "realtime-app.fullname" . }}-mosquitto-config
