apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  labels:
    app.kubernetes.io/name: mqtt
    #app.kubernetes.io/component: mqtt
    {{- include "realtime-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mqtt.service.type }}
  ports:
    - port: {{ .Values.mqtt.service.port }}
      targetPort: {{ .Values.mqtt.service.port }}
      protocol: TCP
      name: mqtt
  selector:
    app.kubernetes.io/name: mqtt
    {{- include "realtime-app.selectorLabels" . | nindent 4 }}