apiVersion: v1
kind: Service
metadata:
  name: processor-service
  labels:
    app.kubernetes.io/name: processor
    {{- include "realtime-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: processor
    {{- include "realtime-app.selectorLabels" . | nindent 4 }}