apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "realtime-app.serviceAccountName" . }}
  labels:
    {{- include "realtime-app.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}