# InfluxDB Configuration
influxdb:
  enabled: true
  image: influxdb:2.7.0
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: local-path
  nodeSelector:
    enabled: true
    key: "kubernetes.io/hostname"
    value: "vishvesh-server-2"

  initialAdminUsername: "admin"
  initialAdminPasswordSecretName: "influxdb-admin-password-secret"
  initialAdminPasswordSecretKey: "password"
  initialAdminTokenSecretName: "influxdb-initial-admin-token-secret"
  initialAdminTokenSecretKey: "token"

  bucket: "delhi-transport-data"
  org: "home"

# MQTT Broker Config
mqtt:
  enabled: true
  image: eclipse-mosquitto:2.0.15
  service:
    type: ClusterIP
    port: 1883


application:
  influxdbTokenSecretName: "influxdb-application-token-secret"
  influxdbTokenSecretKey: "token"

# Data Ingestor Config
ingestor:
  enabled: true
  image: ghcr.io/vishvesh1133/real-time-data-analysis/realtime-ingestor
  imageTag: latest
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
  env:
    FETCH_INTERVAL_SECONDS: "10"
    MQTT_TOPIC: "delhi/transport/raw"
    MQTT_BROKER_HOST: "mqtt-service"
    MQTT_BROKER_PORT: "1883"
    DELHI_OTD_API_KEY_SECRET_NAME: "delhi-otd-api-key-secret"
    DELHI_OTD_API_KEY_SECRET_KEY: "DELHI_OTD_API_KEY"

# Data Processor Config
processor:
  enabled: true
  image: ghcr.io/vishvesh1133/real-time-data-analysis/realtime-processor
  imageTag: latest
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
  env:
    MQTT_TOPIC: "delhi/transport/raw"
    MQTT_BROKER_HOST: "mqtt-service"
    MQTT_BROKER_PORT: "1883"
    INFLUXDB_URL: "http://influxdb-service:8086"
    INFLUXDB_ORG: "home"
    INFLUXDB_BUCKET: "delhi-transport-data"
    INFLUXDB_TOKEN_SECRET_NAME: "{{ .Values.application.influxdbTokenSecretName }}"
    INFLUXDB_TOKEN_SECRET_KEY: "{{ .Values.application.influxdbTokenSecretKey }}"

# Streamlit Dashboard Config
dashboard:
  enabled: true
  image: ghcr.io/vishvesh1133/real-time-data-analysis/realtime-dashboard
  imageTag: latest
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1.5Gi
  env:
    INFLUXDB_URL: "http://influxdb-service:8086"
    INFLUXDB_ORG: "home"
    INFLUXDB_BUCKET: "delhi-transport-data"
    INFLUXDB_TOKEN_SECRET_NAME: "{{ .Values.application.influxdbTokenSecretName }}"
    INFLUXDB_TOKEN_SECRET_KEY: "{{ .Values.application.influxdbTokenSecretKey }}"
  ingress:
    enabled: true
    className: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
      external-dns.alpha.kubernetes.io/hostname: delhirealtime.vishvesh.me
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    host: delhirealtime.vishvesh.me
    path: /
    pathType: Prefix

# General Settings
serviceAccount:
  create: true
  name: "realtime-app-sa"



secrets:

  influxdbInitialAdminPassword:
    name: influxdb-admin-password-secret
    key: password
    value: ""

  influxdbInitialAdminToken:
    name: influxdb-initial-admin-token-secret
    key: token
    value: ""

  influxdbApplicationToken:
    name: influxdb-application-token-secret
    key: token
    value: ""

  # Delhi OTD API Key
  delhiOtdApiKey:
    name: delhi-otd-api-key-secret
    key: DELHI_OTD_API_KEY
    value: ""

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP